# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PrimitiveProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PrimitiveProtocol.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17PrimitiveProtocol.proto\"=\n\x15WorkspaceParamRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x16\n\x0cspecificPath\x18\x02 \x01(\t:\x00\"8\n\x12WorkspacePathReply\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x14\n\x0cisSuccessful\x18\x02 \x02(\x08\x32O\n\x0b\x43mdExecutor\x12@\n\x0f\x43reateWorkspace\x12\x16.WorkspaceParamRequest\x1a\x13.WorkspacePathReply\"\x00'
)




_WORKSPACEPARAMREQUEST = _descriptor.Descriptor(
  name='WorkspaceParamRequest',
  full_name='WorkspaceParamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='WorkspaceParamRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='specificPath', full_name='WorkspaceParamRequest.specificPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=88,
)


_WORKSPACEPATHREPLY = _descriptor.Descriptor(
  name='WorkspacePathReply',
  full_name='WorkspacePathReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='WorkspacePathReply.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isSuccessful', full_name='WorkspacePathReply.isSuccessful', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['WorkspaceParamRequest'] = _WORKSPACEPARAMREQUEST
DESCRIPTOR.message_types_by_name['WorkspacePathReply'] = _WORKSPACEPATHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkspaceParamRequest = _reflection.GeneratedProtocolMessageType('WorkspaceParamRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACEPARAMREQUEST,
  '__module__' : 'PrimitiveProtocol_pb2'
  # @@protoc_insertion_point(class_scope:WorkspaceParamRequest)
  })
_sym_db.RegisterMessage(WorkspaceParamRequest)

WorkspacePathReply = _reflection.GeneratedProtocolMessageType('WorkspacePathReply', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACEPATHREPLY,
  '__module__' : 'PrimitiveProtocol_pb2'
  # @@protoc_insertion_point(class_scope:WorkspacePathReply)
  })
_sym_db.RegisterMessage(WorkspacePathReply)



_CMDEXECUTOR = _descriptor.ServiceDescriptor(
  name='CmdExecutor',
  full_name='CmdExecutor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateWorkspace',
    full_name='CmdExecutor.CreateWorkspace',
    index=0,
    containing_service=None,
    input_type=_WORKSPACEPARAMREQUEST,
    output_type=_WORKSPACEPATHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CMDEXECUTOR)

DESCRIPTOR.services_by_name['CmdExecutor'] = _CMDEXECUTOR

# @@protoc_insertion_point(module_scope)
